################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Include Pipeline Templates
include:
  - remote: 'https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/gitlab/php/connectors.yaml'

#################################################################
# Quality Tests
#################################################################

quality:php-8.1:
  when: manual

#################################################################
# Functional Tests
#################################################################

functional:php-8.1:
  when: manual

functional:php-8.2:
  when: manual

################################################################################
# Functional Tests - ThirdParty & Address
functional:customers:
    extends:            functional:php-8.1
    when:               always
    variables:
        SPLASH_TYPES:   "ThirdParty,Address"

################################################################################
# Functional Tests - Products
functional:products:
    extends:            functional:php-8.1
    when:               always
    needs:
        - functional:customers
    variables:
        SPLASH_TYPES:   "Product"

################################################################################
# Functional Tests - Orders & Invoices
functional:orders:
    extends:            functional:php-8.1
    when:               always
    needs:
        - functional:customers
        - functional:products
    variables:
        SPLASH_TYPES:   "Order,Invoice"
