parameters:
    splash.connectors.shopify.api-secret: '%env(resolve:SHOPIFY_API_SECRET)%'

services:
    ################################################################################
    # SPLASH Shopify Connector Service
    splash.connectors.shopify:
        class: Splash\Connectors\Shopify\Services\ShopifyConnector
        autowire: true
        arguments:
            - "%kernel.cache_dir%"
            - "%splash.connectors.shopify.api-secret%"
        tags:
            - { name: "splash.connector"}

    ################################################################################
    # SPLASH Shopify WebHooks Manager
    Splash\Connectors\Shopify\Services\WebhooksManager:
        autowire: true

    ################################################################################
    # Enables Dependency Injection in Controller Actions
    Splash\Connectors\Shopify\Controller\:
        resource: '../../Controller'
        public: true
        autowire: true
        tags: ['controller.service_arguments']