services:

    _defaults:
        autowire: true

    ################################################################################
    # SPLASH Shopify Connector Service
    splash.connectors.shopify:
        class: Splash\Connectors\Shopify\Services\ShopifyConnector
        autowire: true
        arguments:
            $cacheDir:  "%kernel.cache_dir%"
        tags:
            - { name: "splash.connector"}

    Splash\Connectors\Shopify\Services\ShopifyConnector:
        alias: splash.connectors.shopify

    ################################################################################
    # SPLASH Shopify Scopes Manager
    Splash\Connectors\Shopify\Services\ScopesManagers: ~

    ################################################################################
    # SPLASH Shopify WebHooks Manager
    Splash\Connectors\Shopify\Services\WebhooksManager: ~

    ################################################################################
    # Enables Dependency Injection in Controller Actions
    Splash\Connectors\Shopify\Controller\:
        resource: '../../Controller'
        public: true
        autowire: true
        tags: ['controller.service_arguments']

    ################################################################################
    # Register Connector Authenticator to Connect from Shopify Admin
    Splash\Connectors\Shopify\OAuth2\ShopifyAuthenticator:
        tags: ['splash.connectors.authenticator']
