
splash:

################################################################################    
# Configure Splash Bundle Parameters Cache    
# Cache is Enabled by Default to Store Custom Connectors Configuration
# If disabled, configuration must be store in Static, on connections section
################################################################################    
#    cache: 
#        enabled: false    
#        lifetime: 10

    # Allow Notifications for Generic Users   
    notify: ["ROLE_USER"]
    
################################################################################    
# List of Available Connector Connections
################################################################################    

    connections:
        
        ########################################################################
        # Shopify Connection
        shopify:
            id:                 ThisIsShopifyWsId
            key:                ThisIsNotASecretKeyForShopify
            name:               Shopify Server
            host:               false
            connector:          shopify
            config:
                WsHost:         '%env(resolve:SHOPIFY_URL)%'
                LocationId:     '%env(resolve:SHOPIFY_LOCATION)%'
                Token:          '%env(resolve:SHOPIFY_PRIVATE_TOKEN)%'
                Extended:       true
                LogisticMode:   true
